runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
  application_readable: true
- url: /.*
  script: main.app


env_variables:
    CLOUDSQL_CONNECTION_NAME: babelli-gutenberg-copypasta:us-central1:babelli-library
    CLOUDSQL_USER: root

libraries:
- name: MySQLdb
  version: "latest"
